spring.application.name=demo


# Formato: mongodb://host1:port1,host2:port2,host3:port3/base_de_datos?replicaSet=nombre_del_set
spring.data.mongodb.uri=mongodb://localhost:27017,localhost:27018,localhost:27019/mi_base_datos?replicaSet=rs0&retryWrites=true&retryReads=true

logging.level.org.springframework.boot.autoconfigure.mongo=TRACE