spring.application.name=demo

spring.data.mongodb.uri=mongodb://mongo1:27017,mongo2:27017,mongo3:27017/mi_base_datos?replicaSet=rs0&retryWrites=true&retryReads=true
logging.level.org.springframework.boot.autoconfigure.mongo=TRACE