spring.application.name=demo

spring.data.mongodb.uri=mongodb://mongo1:27017,mongo2:27017,mongo3:27017/lab_messaging_app?replicaSet=rs0&retryWrites=true
logging.level.org.springframework.boot.autoconfigure.mongo=TRACE